### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by MateoLa** [spree-contrib/spree_volume_pricing#125]
After adding the gem to my gemfile if I  run:

``
  rails generate spree_volume_pricing:install
``

I get the error:

../.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require': cannot load such file -- coffee_script (LoadError)

The required "coffee_script" is in /lib/spree_volume_pricing.rb
Gem coffee-rails has its reported status as failing (https://github.com/rails/coffee-rails)

You can remove this requirement because all the javascript files are written in jquery.

**Comment by damianlegawiec** [comment]
Fixed
