### ISSUE TITLE
 Bug is not updating my cart correctly

### ISSUE THREAD

**Issue by picazoH** [spree-contrib/spree_volume_pricing#38]
If I change to a inferior range vprice, the quantity price is not applied correctly in the shopping cart.
 affecting 1-3-stable and master, line_item_decorator.rb

  if (!new_price.nil? and vprice <= new_price) or vprice <= self.price 
  
  The following code is missing in the conditional...
  or vprice >= self.price

**Comment by jspizziri** [comment]
@picazoH, are you still experiencing this issue?

Its very old and if the issue isn't reconfirmed I'm going to close it.
