### ISSUE TITLE
master branch is broken for spree 2.3.0.beta when editing variants to add volume prices

### ISSUE THREAD

**Issue by frankiek3** [spree-contrib/spree_volume_pricing#62]
there are no field rows when first viewing the edit page and no rows can be created
this stems from the javascript row cloning but I don't know why it broke for spree 2.3.0.beta
it should be able to create a row when no row existed (if a user removes all rows and starts from scratch)

I made a github fork with a new javascript function

**Comment by JDutil** [comment]
out of date
