### ISSUE TITLE
Proposed New Features - Pricing Models & Roles

### ISSUE THREAD

**Issue by jspizziri** [spree-contrib/spree_volume_pricing#72]
First, great work guys, thank you for building this gem.

There are a few features that I would like to propose that be built (I'm not opposed to contributing).

1. Abstract the volume prices a bit by providing attaching them to a Volume Pricing Model, attach the model to the variants rather than the volume prices themselves. This would allow the definition of a few abstract pricing models that could be applied to N products/variants. Updates on each pricing model would propagate to every item using that model.

2. Add the ability to specify a role on volume prices/volume pricing models. This would allow different pricing models for different users, which is necessary in the case of wholesaling etc.

3. I saw another issue https://github.com/spree-contrib/spree_volume_pricing/issues/45, which discussed adding a volume pricing to the product which would be applied for every variant belonging to that product. I similarly think this would be a good idea, and perhaps a good build to roll it up into.

What say you?

**Comment by juancroca** [comment]
+1

**Comment by jspizziri** [comment]
https://github.com/spree-contrib/spree_volume_pricing/pull/76
