### ISSUE TITLE
String#to_range not working properly

### ISSUE THREAD

**Issue by AKnopf** [spree-contrib/spree_volume_pricing#81]
Hello everyone.

reproduce:
bundle exec rails console
"10..20".to_range # => 0..20 but should be 10..20

The first digit of the first number is ignored.

The error is in engine.rb the two `from`-calls in lines 17 and 20 should just not be there.

**Comment by QuintinAdam** [comment]
"(10..20)".to_range # => 10..20

Surrounding it will give you your desired output.  

I feel like it should be able to work both ways though.

**Comment by futhr** [comment]
Hi @AKnopf You may verify and close if #82 fixed this.

**Comment by jspizziri** [comment]
@AKnopf, did #82 fix this?

**Comment by jspizziri** [comment]
@AKnopf, I'm closing this issue unless you verify that #82 did not fix this issue.

**Comment by AKnopf** [comment]
Sorry it took so long. The PR indeed fixed the problem. Good work!

Thanks for the quick reply!
